apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sbrdwx957-python 
  janus-idp.io/tekton: sbrdwx957-python
  backstage.io/kubernetes-id: sbrdwx957-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sbrdwx957-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  